### ISSUE TITLE
Remove web and wiro modules

### ISSUE THREAD

**Issue by bytecodeguru** [buildo/toctoc#67]
## requirements
{describe the new feature}

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

**Comment by ecamellini** [comment]
@bytecodeguru random proposals for this refactor:
- removing from the scope of toctoc the front-end part, and maybe also the Scala controller part, refactoring it to be just a Scala service (that, if needed, could be also spawned as a separate micro service instead of being used as a library, as @boh717 proposed). Such service would be used to handle authentication/authorization/roles logics around the backend app (starting just with auth, for feature parity with what we have now). It is then up to the app that uses toctoc to expose it through a controller, generate routes, generate the front-end part using metarpheus, etc. This would also simplify the release process: we would have to release just a scala library (e.g., this would be automatically solved https://github.com/buildo/toctoc/issues/32).
- as part of this work, we could also forget about quill since not part of our stack anymore and since we don't plan to use it in other projects
- we can address this too since we are refactoring https://github.com/buildo/toctoc/issues/59

**Comment by bytecodeguru** [comment]
@ecamellini what about having a multi module project? We could have `toctoc-core`, `toctoc-wiro` for example, so projects would import just what they need.

**Comment by ecamellini** [comment]
@bytecodeguru that could make sense too; would you still leave the metarpheus part up to the project or include also a front-end module (basically, the metarpheus generated part, like there is right now)?

**Comment by bytecodeguru** [comment]
Given the different release process, perhaps it could be better to separate the frontend code (metarpheus, react components, session management, etc) into a separate project.
FE and BE should be coupled only at the HTTP API level, so they could evolve independently from each other. What do you think?

**Comment by ecamellini** [comment]
Makes sense, or even just not have a library for it (there is not so much logic on the front-end, if you exclude the ones automagically generated). @giogonzo thoughts on this?

**Comment by giogonzo** [comment]
agreed, it'd be even simpler from a FE perspective than now if the toctoc routes are just generated as part of the standard metarpheus step, exposed by the API as any other route (currently we have to merge the two sets of routes manually).
Also, as of now we have to update an additional repo when we have changes in metarpheus(-io-ts).

I don't think the rest of the TS code is currently used in any FE project (`SessionSerializer`)? @veej ?

**Comment by gabro** [comment]
Here's a proposal, trying to recap what discussed both here and offline:

- remove the controller part. The gains are little, and copy-pasting from an example is probably as effective. Also, it's then easier to integrate with the existing metarpheus setup of a project
- remove the front-end part of the library completely

If you agree, I can work on this asap.

**Comment by bytecodeguru** [comment]
It's ok for me to limit the scope of this refactor to what @gabro proposed.
Let's track further improvements in separate PRs (tagless final, better abstractions etc etc)

**Comment by ecamellini** [comment]
@gabro okay for me too.
